// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PrimeCheck
type PrimeCheck struct {
	ID        int32     `json:"id"`
	Number    string    `json:"number"`
	CreatedAt time.Time `json:"created_at"`
	TraceID   OptString `json:"trace_id"`
	MessageID OptString `json:"message_id"`
	IsPrime   OptBool   `json:"is_prime"`
	Status    OptString `json:"status"`
}

// GetID returns the value of ID.
func (s *PrimeCheck) GetID() int32 {
	return s.ID
}

// GetNumber returns the value of Number.
func (s *PrimeCheck) GetNumber() string {
	return s.Number
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PrimeCheck) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetTraceID returns the value of TraceID.
func (s *PrimeCheck) GetTraceID() OptString {
	return s.TraceID
}

// GetMessageID returns the value of MessageID.
func (s *PrimeCheck) GetMessageID() OptString {
	return s.MessageID
}

// GetIsPrime returns the value of IsPrime.
func (s *PrimeCheck) GetIsPrime() OptBool {
	return s.IsPrime
}

// GetStatus returns the value of Status.
func (s *PrimeCheck) GetStatus() OptString {
	return s.Status
}

// SetID sets the value of ID.
func (s *PrimeCheck) SetID(val int32) {
	s.ID = val
}

// SetNumber sets the value of Number.
func (s *PrimeCheck) SetNumber(val string) {
	s.Number = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PrimeCheck) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetTraceID sets the value of TraceID.
func (s *PrimeCheck) SetTraceID(val OptString) {
	s.TraceID = val
}

// SetMessageID sets the value of MessageID.
func (s *PrimeCheck) SetMessageID(val OptString) {
	s.MessageID = val
}

// SetIsPrime sets the value of IsPrime.
func (s *PrimeCheck) SetIsPrime(val OptBool) {
	s.IsPrime = val
}

// SetStatus sets the value of Status.
func (s *PrimeCheck) SetStatus(val OptString) {
	s.Status = val
}

// Ref: #/components/schemas/PrimeCheckInput
type PrimeCheckInput struct {
	Number string `json:"number"`
}

// GetNumber returns the value of Number.
func (s *PrimeCheckInput) GetNumber() string {
	return s.Number
}

// SetNumber sets the value of Number.
func (s *PrimeCheckInput) SetNumber(val string) {
	s.Number = val
}

// Ref: #/components/schemas/PrimeCheckList
type PrimeCheckList struct {
	Items []PrimeCheck `json:"items"`
}

// GetItems returns the value of Items.
func (s *PrimeCheckList) GetItems() []PrimeCheck {
	return s.Items
}

// SetItems sets the value of Items.
func (s *PrimeCheckList) SetItems(val []PrimeCheck) {
	s.Items = val
}

// Ref: #/components/schemas/Setting
type Setting struct {
	RecordNumberSuccess bool `json:"record_number_success"`
	PrimeCheckSuccess   bool `json:"prime_check_success"`
	EmailSendSuccess    bool `json:"email_send_success"`
	DlqSaveSuccess      bool `json:"dlq_save_success"`
}

// GetRecordNumberSuccess returns the value of RecordNumberSuccess.
func (s *Setting) GetRecordNumberSuccess() bool {
	return s.RecordNumberSuccess
}

// GetPrimeCheckSuccess returns the value of PrimeCheckSuccess.
func (s *Setting) GetPrimeCheckSuccess() bool {
	return s.PrimeCheckSuccess
}

// GetEmailSendSuccess returns the value of EmailSendSuccess.
func (s *Setting) GetEmailSendSuccess() bool {
	return s.EmailSendSuccess
}

// GetDlqSaveSuccess returns the value of DlqSaveSuccess.
func (s *Setting) GetDlqSaveSuccess() bool {
	return s.DlqSaveSuccess
}

// SetRecordNumberSuccess sets the value of RecordNumberSuccess.
func (s *Setting) SetRecordNumberSuccess(val bool) {
	s.RecordNumberSuccess = val
}

// SetPrimeCheckSuccess sets the value of PrimeCheckSuccess.
func (s *Setting) SetPrimeCheckSuccess(val bool) {
	s.PrimeCheckSuccess = val
}

// SetEmailSendSuccess sets the value of EmailSendSuccess.
func (s *Setting) SetEmailSendSuccess(val bool) {
	s.EmailSendSuccess = val
}

// SetDlqSaveSuccess sets the value of DlqSaveSuccess.
func (s *Setting) SetDlqSaveSuccess(val bool) {
	s.DlqSaveSuccess = val
}
