// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	PrimeChecksCreateOperation OperationName = "PrimeChecksCreate"
	PrimeChecksGetOperation    OperationName = "PrimeChecksGet"
	PrimeChecksListOperation   OperationName = "PrimeChecksList"
	SettingsCreateOperation    OperationName = "SettingsCreate"
	SettingsGetOperation       OperationName = "SettingsGet"
)
