services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nats:
    image: nats:2.11-alpine
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"  # HTTP monitoring port
    command: >
      --js
      --store_dir /data
      --http_port 8222
    volumes:
      - nats_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/"]
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  web-server:
    build:
      context: docker/local
      dockerfile: web-server.local.Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  outbox-publisher:
    build:
      context: docker/local
      dockerfile: outbox-publisher.local.Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NATS_URL: nats://nats:4222
    depends_on:
      mysql:
        condition: service_healthy
      nats:
        condition: service_healthy    

  prime-check-worker:
    build:
      context: docker/local
      dockerfile: prime-check-worker.local.Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NATS_URL: nats://nats:4222
    depends_on:
      mysql:
        condition: service_healthy
      nats:
        condition: service_healthy

  email-send-worker:
    build:
      context: docker/local
      dockerfile: email-send-worker.local.Dockerfile
    restart: unless-stopped
    environment:
      NATS_URL: nats://nats:4222
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP}
    depends_on:
      nats:
        condition: service_healthy
      mailpit:
        condition: service_started

volumes:
  mysql_data:
  nats_data: