// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	PrimeTestsCreateOperation OperationName = "PrimeTestsCreate"
	PrimeTestsGetOperation    OperationName = "PrimeTestsGet"
	PrimeTestsListOperation   OperationName = "PrimeTestsList"
	SettingsCreateOperation   OperationName = "SettingsCreate"
	SettingsGetOperation      OperationName = "SettingsGet"
)
