// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// PrimeChecksGetParams is parameters of PrimeChecks_get operation.
type PrimeChecksGetParams struct {
	RequestID int32
}

func unpackPrimeChecksGetParams(packed middleware.Parameters) (params PrimeChecksGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "request_id",
			In:   "path",
		}
		params.RequestID = packed[key].(int32)
	}
	return params
}

func decodePrimeChecksGetParams(args [1]string, argsEscaped bool, r *http.Request) (params PrimeChecksGetParams, _ error) {
	// Decode path: request_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "request_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.RequestID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "request_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
