// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PrimeTestsCreate implements PrimeTests_create operation.
//
// POST /primality-tests
func (UnimplementedHandler) PrimeTestsCreate(ctx context.Context, req *PrimeTestRequest) (r *PrimeTest, _ error) {
	return r, ht.ErrNotImplemented
}

// PrimeTestsGet implements PrimeTests_get operation.
//
// GET /primality-tests/{request_id}
func (UnimplementedHandler) PrimeTestsGet(ctx context.Context, params PrimeTestsGetParams) (r *PrimeTest, _ error) {
	return r, ht.ErrNotImplemented
}

// PrimeTestsList implements PrimeTests_list operation.
//
// GET /primality-tests
func (UnimplementedHandler) PrimeTestsList(ctx context.Context) (r *PrimeTestList, _ error) {
	return r, ht.ErrNotImplemented
}

// SettingsCreate implements Settings_create operation.
//
// POST /settings
func (UnimplementedHandler) SettingsCreate(ctx context.Context, req *Setting) (r *Setting, _ error) {
	return r, ht.ErrNotImplemented
}

// SettingsGet implements Settings_get operation.
//
// GET /settings
func (UnimplementedHandler) SettingsGet(ctx context.Context) (r *Setting, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
