// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/PrimeCheck
type PrimeCheck struct {
	ID        int32     `json:"id"`
	Number    string    `json:"number"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *PrimeCheck) GetID() int32 {
	return s.ID
}

// GetNumber returns the value of Number.
func (s *PrimeCheck) GetNumber() string {
	return s.Number
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PrimeCheck) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *PrimeCheck) SetID(val int32) {
	s.ID = val
}

// SetNumber sets the value of Number.
func (s *PrimeCheck) SetNumber(val string) {
	s.Number = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PrimeCheck) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/PrimeCheckInput
type PrimeCheckInput struct {
	Number string `json:"number"`
}

// GetNumber returns the value of Number.
func (s *PrimeCheckInput) GetNumber() string {
	return s.Number
}

// SetNumber sets the value of Number.
func (s *PrimeCheckInput) SetNumber(val string) {
	s.Number = val
}

// Ref: #/components/schemas/PrimeCheckList
type PrimeCheckList struct {
	Items []PrimeCheck `json:"items"`
}

// GetItems returns the value of Items.
func (s *PrimeCheckList) GetItems() []PrimeCheck {
	return s.Items
}

// SetItems sets the value of Items.
func (s *PrimeCheckList) SetItems(val []PrimeCheck) {
	s.Items = val
}

// Ref: #/components/schemas/Setting
type Setting struct {
	RecordNumberSuccess bool `json:"record_number_success"`
	PrimeRequestSuccess bool `json:"prime_request_success"`
	EmailSendSuccess    bool `json:"email_send_success"`
	DlqSaveSuccess      bool `json:"dlq_save_success"`
}

// GetRecordNumberSuccess returns the value of RecordNumberSuccess.
func (s *Setting) GetRecordNumberSuccess() bool {
	return s.RecordNumberSuccess
}

// GetPrimeRequestSuccess returns the value of PrimeRequestSuccess.
func (s *Setting) GetPrimeRequestSuccess() bool {
	return s.PrimeRequestSuccess
}

// GetEmailSendSuccess returns the value of EmailSendSuccess.
func (s *Setting) GetEmailSendSuccess() bool {
	return s.EmailSendSuccess
}

// GetDlqSaveSuccess returns the value of DlqSaveSuccess.
func (s *Setting) GetDlqSaveSuccess() bool {
	return s.DlqSaveSuccess
}

// SetRecordNumberSuccess sets the value of RecordNumberSuccess.
func (s *Setting) SetRecordNumberSuccess(val bool) {
	s.RecordNumberSuccess = val
}

// SetPrimeRequestSuccess sets the value of PrimeRequestSuccess.
func (s *Setting) SetPrimeRequestSuccess(val bool) {
	s.PrimeRequestSuccess = val
}

// SetEmailSendSuccess sets the value of EmailSendSuccess.
func (s *Setting) SetEmailSendSuccess(val bool) {
	s.EmailSendSuccess = val
}

// SetDlqSaveSuccess sets the value of DlqSaveSuccess.
func (s *Setting) SetDlqSaveSuccess(val bool) {
	s.DlqSaveSuccess = val
}
