// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// PrimeTestsCreate implements PrimeTests_create operation.
	//
	// POST /primality-tests
	PrimeTestsCreate(ctx context.Context, req *PrimeTestRequest) (*PrimeTest, error)
	// PrimeTestsGet implements PrimeTests_get operation.
	//
	// GET /primality-tests/{request_id}
	PrimeTestsGet(ctx context.Context, params PrimeTestsGetParams) (*PrimeTest, error)
	// PrimeTestsList implements PrimeTests_list operation.
	//
	// GET /primality-tests
	PrimeTestsList(ctx context.Context) (*PrimeTestList, error)
	// SettingsCreate implements Settings_create operation.
	//
	// POST /settings
	SettingsCreate(ctx context.Context, req *Setting) (*Setting, error)
	// SettingsGet implements Settings_get operation.
	//
	// GET /settings
	SettingsGet(ctx context.Context) (*Setting, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
