// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PrimeChecksCreate implements PrimeChecks_create operation.
//
// POST /prime-check
func (UnimplementedHandler) PrimeChecksCreate(ctx context.Context, req *PrimeCheckInput) (r *PrimeCheck, _ error) {
	return r, ht.ErrNotImplemented
}

// PrimeChecksGet implements PrimeChecks_get operation.
//
// GET /prime-check/{request_id}
func (UnimplementedHandler) PrimeChecksGet(ctx context.Context, params PrimeChecksGetParams) (r *PrimeCheck, _ error) {
	return r, ht.ErrNotImplemented
}

// PrimeChecksList implements PrimeChecks_list operation.
//
// GET /prime-check
func (UnimplementedHandler) PrimeChecksList(ctx context.Context) (r *PrimeCheckList, _ error) {
	return r, ht.ErrNotImplemented
}

// SettingsCreate implements Settings_create operation.
//
// POST /settings
func (UnimplementedHandler) SettingsCreate(ctx context.Context, req *Setting) (r *Setting, _ error) {
	return r, ht.ErrNotImplemented
}

// SettingsGet implements Settings_get operation.
//
// GET /settings
func (UnimplementedHandler) SettingsGet(ctx context.Context) (r *Setting, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
