root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/prime-check-worker"
  cmd = "go build -o ./tmp/prime-check-worker ./cmd/prime-check-worker"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  delay = 1000

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false