// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package generated_sql

import (
	"time"
)

type Book struct {
	ID          int32
	Title       string
	Author      string
	PublishedAt time.Time
	CreatedAt   time.Time
}

type Chapter struct {
	ID        int32
	BookID    int32
	Number    int32
	Content   string
	CreatedAt time.Time
}
